site_name: Docs Chavinci


theme:
  name: material
  custom_dir: overrides
  palette:
    primary: custom
    scheme: slate
  language: en 
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  logo: assets/logo.png
  favicon: assets/images/favicon.png

nav:
  - Home: index.md
  - Overview: 
    - Learn: overview/learn.md
    - Getting Started: overview/getting-stared.md
    - Network: overview/network.md
    - Glossary: overview/glossary.md
  - Wallet: 
    - Desktop Wallet: wallet/desktop.md
    - Mobile Wallet: wallet/mobile.md
  - Developer:
    - Full Node: developer/node.md
    - Staking: developer/staking.md
    - Token Metadata: developer/metadata.md
    - Atomic Swaps: developer/atomic.md
    - RPC: developer/rpc.md
  
  - Blog & FAQ's:
    - Blog: 
      - First Blog: blog/first-blog.md
    - FAQ: faq.md
     
  - Company: company.md


    

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
    
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ChavinciNetwork
    - icon: fontawesome/brands/github
      link: https://github.com/chavinci-chain
    - icon: fontawesome/brands/medium
      link: https://medium.com/@chavinci
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/chavinci/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/zfJEzYEnVD

# Copyright
copyright: Copyright &copy; 2023 Chavinci

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - admonition

