site_name: Docs Chavinci
site_description: >-
  Welcome to the Chavinci Documentation! We're excited to guide you through the innovative world of Chavinci, where blockchain technology meets unparalleled ease of use and security. Dive into our comprehensive guides to discover how Chavinci is reshaping the blockchain landscape, making it more accessible, secure, and efficient for everyone. Whether you're a seasoned blockchain expert or just beginning your journey, our documentation will provide you with all the resources you need to navigate and leverage the full potential of the Chavinci ecosystem. You can start the journey by setting up your node in 5 minutes.


theme:
  name: material
  custom_dir: overrides
  palette:
    primary: custom
    scheme: slate
 
  language: en 
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.share
    - content.code.copy
    - navigation.footer
    - navigation.indexes
   
  logo: assets/logo.png
  favicon: assets/images/favico.png


plugins:
  - blog 
  - tags:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true


extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ChavinciNetwork
    - icon: fontawesome/brands/github
      link: https://github.com/chavinci-chain
    - icon: fontawesome/brands/medium
      link: https://medium.com/@chavinci
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/chavinci/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/zfJEzYEnVD

  analytics: 
    provider: google
    property: G-ZFDC0ZZWFD
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  


markdown_extensions:

  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

nav:
  
  - Overview: 
    - overview/index.md
    - Key Features : overview/key-features.md
    - The Octopus Labs Vision: overview/the-octopus-labs-vision.md
    - MLT and Cha PoS v3.0: overview/mlt-and-cha-pos-v3.0.md
    - User-Centric Approach: overview/user-centric-approach.md
    - D-Mail System: overview/d-mail-system.md
    - Security and Accessibility: overview/security-and-accessibility.md
    - Glossary: https://chavinci.com/glossary
  - Wallet: 
    - Cha Core Wallet: wallet/chaCoreWallet.md
    - Mobile Wallet: wallet/mobile.md
  - Developer:
    - Run a Node: 
      - developer/node/node.md
      - Manually Setup: developer/node/manually-setup.md
      - Console RPC Functions: developer/node/rpc-functions.md
    - Staking: developer/staking.md
    - Token Metadata: developer/metadata.md
    - Atomic Swaps: developer/atomic.md
    - RPC: developer/rpc.md
  
  - Blog & FAQ's:
    - Blog:
      - blog/index.md
    - FAQ: faq.md
     
  - Company: 
    - company/index.md
    - Chavinci's Journey: company/chavincis-journey.md
    - Corporate Responsibility: company/corporate-responsibility.md
    - Innovation and Technology at Chavinci: company/innovation-and-technology-at-chavinci.md
    - Company Culture and Careers: company/company-culture-and-careers.md
    - Press and Media Resources: company/press-and-media-resources.md
    - Contact Information: company/contact-information.md
     


    


# Copyright
copyright: Copyright &copy; 2024 Chavinci Network

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - admonition
