site_name: Docs Chavinci
site_description: >-
  Chavinci Network is embarking on a journey with Proof-of-Stake 3.0 (Pos3), a technology that is revolutionizing the blockchain world. 
  Pos3 is one of the main features that distinguishes Chavinci Network from other blockchain projects, going beyond previous generations in energy efficiency, speed and security


theme:
  name: material
  custom_dir: overrides
  palette:
    primary: custom
    scheme: slate
 
  language: en 
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.share
    - content.code.copy
    - navigation.footer
    - navigation.indexes
   
  logo: assets/logo.png
  favicon: assets/images/favico.png


plugins:
  - blog 
  - tags:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true


extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ChavinciNetwork
    - icon: fontawesome/brands/github
      link: https://github.com/chavinci-chain
    - icon: fontawesome/brands/medium
      link: https://medium.com/@chavinci
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/chavinci/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/zfJEzYEnVD

  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  


markdown_extensions:

  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

nav:
  
  - Overview: 
    - overview/index.md
    - Key Features : overview/key-features.md
    - The Octopus Labs Vision: overview/the-octopus-labs-vision.md
    - MLT and Cha PoS v3.0: overview/mlt-and-cha-pos-v3.0.md
    - User-Centric Approach: overview/user-centric-approach.md
    - D-Mail System: overview/d-mail-system.md
    - Security and Accessibility: overview/security-and-accessibility.md
    - Glossary: https://chavinci.com/glossary
  - Wallet: 
    - Desktop Wallet: wallet/desktop.md
    - Mobile Wallet: wallet/mobile.md
  - Developer:
    - Full Node: developer/node.md
    - Staking: developer/staking.md
    - Token Metadata: developer/metadata.md
    - Atomic Swaps: developer/atomic.md
    - RPC: developer/rpc.md
  
  - Blog & FAQ's:
    - Blog:
      - blog/index.md
    - FAQ: faq.md
     
  - Company: 
    - company/index.md
    - Chavinci's Journey: company/chavincis-journey.md
    - Corporate Responsibility: company/corporate-responsibility.md
    - Innovation and Technology at Chavinci: company/innovation-and-technology-at-chavinci.md
    - Company Culture and Careers: company/company-culture-and-careers.md
    - Press and Media Resources: company/press-and-media-resources.md
    - Contact Information: company/contact-information.md
     


    


# Copyright
copyright: Copyright &copy; 2023 Chavinci Network

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - admonition

